# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(498, 497)
        self.Queue = QtWidgets.QTextBrowser(parent=Form)
        self.Queue.setGeometry(QtCore.QRect(12, 279, 474, 71))
        self.Queue.setObjectName("Queue")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 360, 60, 16))
        self.label.setObjectName("label")
        self.Server = QtWidgets.QTextBrowser(parent=Form)
        self.Server.setGeometry(QtCore.QRect(12, 12, 474, 79))
        self.Server.setObjectName("Server")
        self.Producer = QtWidgets.QTextBrowser(parent=Form)
        self.Producer.setGeometry(QtCore.QRect(12, 101, 474, 79))
        self.Producer.setObjectName("Producer")
        self.Consumer = QtWidgets.QTextBrowser(parent=Form)
        self.Consumer.setGeometry(QtCore.QRect(12, 190, 474, 79))
        self.Consumer.setObjectName("Consumer")
        self.NumberBox = QtWidgets.QLineEdit(parent=Form)
        self.NumberBox.setGeometry(QtCore.QRect(90, 360, 391, 21))
        self.NumberBox.setObjectName("NumberBox")
        self.openServer = QtWidgets.QPushButton(parent=Form)
        self.openServer.setGeometry(QtCore.QRect(6, 393, 481, 32))
        self.openServer.setObjectName("openServer")
        self.openProducer = QtWidgets.QPushButton(parent=Form)
        self.openProducer.setGeometry(QtCore.QRect(6, 427, 481, 32))
        self.openProducer.setObjectName("openProducer")
        self.openConsumer = QtWidgets.QPushButton(parent=Form)
        self.openConsumer.setGeometry(QtCore.QRect(6, 461, 481, 32))
        self.openConsumer.setObjectName("openConsumer")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Number:"))
        self.openServer.setText(_translate("Form", "OpenServer"))
        self.openProducer.setText(_translate("Form", "OpenProducer"))
        self.openConsumer.setText(_translate("Form", "OpenConsumer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
