# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(568, 458)
        self.displayBox = QtWidgets.QTextBrowser(parent=Form)
        self.displayBox.setGeometry(QtCore.QRect(20, 10, 531, 192))
        self.displayBox.setObjectName("displayBox")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(11, 313, 117, 16))
        self.label_10.setObjectName("label_10")
        self.listMailNumber = QtWidgets.QLineEdit(parent=Form)
        self.listMailNumber.setGeometry(QtCore.QRect(136, 282, 411, 21))
        self.listMailNumber.setObjectName("listMailNumber")
        self.listMail = QtWidgets.QPushButton(parent=Form)
        self.listMail.setGeometry(QtCore.QRect(15, 381, 261, 32))
        self.listMail.setObjectName("listMail")
        self.deleteMail = QtWidgets.QPushButton(parent=Form)
        self.deleteMail.setGeometry(QtCore.QRect(272, 347, 281, 32))
        self.deleteMail.setObjectName("deleteMail")
        self.quit = QtWidgets.QPushButton(parent=Form)
        self.quit.setGeometry(QtCore.QRect(272, 415, 281, 32))
        self.quit.setObjectName("quit")
        self.showMailContext = QtWidgets.QPushButton(parent=Form)
        self.showMailContext.setGeometry(QtCore.QRect(272, 381, 281, 32))
        self.showMailContext.setObjectName("showMailContext")
        self.deleteMailNumber = QtWidgets.QLineEdit(parent=Form)
        self.deleteMailNumber.setGeometry(QtCore.QRect(136, 313, 411, 21))
        self.deleteMailNumber.setObjectName("deleteMailNumber")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(11, 282, 99, 16))
        self.label_11.setObjectName("label_11")
        self.password = QtWidgets.QLineEdit(parent=Form)
        self.password.setGeometry(QtCore.QRect(136, 251, 411, 21))
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(parent=Form)
        self.username.setGeometry(QtCore.QRect(136, 220, 411, 21))
        self.username.setObjectName("username")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(11, 220, 68, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(11, 251, 63, 16))
        self.label_2.setObjectName("label_2")
        self.logIn = QtWidgets.QPushButton(parent=Form)
        self.logIn.setGeometry(QtCore.QRect(15, 347, 261, 32))
        self.logIn.setObjectName("logIn")
        self.listMailDetail = QtWidgets.QPushButton(parent=Form)
        self.listMailDetail.setGeometry(QtCore.QRect(15, 415, 261, 32))
        self.listMailDetail.setObjectName("listMailDetail")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_10.setText(_translate("Form", "DeleteMailNumber:"))
        self.listMail.setText(_translate("Form", "ListMailNumber"))
        self.deleteMail.setText(_translate("Form", "DeleteMail"))
        self.quit.setText(_translate("Form", "Quit"))
        self.showMailContext.setText(_translate("Form", "ShowMailContext"))
        self.label_11.setText(_translate("Form", "ListMailNumber:"))
        self.label.setText(_translate("Form", "UserName:"))
        self.label_2.setText(_translate("Form", "Password:"))
        self.logIn.setText(_translate("Form", "LogIn"))
        self.listMailDetail.setText(_translate("Form", "ListMailDetail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
