# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(571, 599)
        self.displayBox = QtWidgets.QTextBrowser(parent=Form)
        self.displayBox.setGeometry(QtCore.QRect(20, 10, 531, 192))
        self.displayBox.setObjectName("displayBox")
        self.create = QtWidgets.QPushButton(parent=Form)
        self.create.setGeometry(QtCore.QRect(10, 520, 251, 32))
        self.create.setObjectName("create")
        self.reply = QtWidgets.QPushButton(parent=Form)
        self.reply.setGeometry(QtCore.QRect(277, 486, 271, 32))
        self.reply.setObjectName("reply")
        self.quit = QtWidgets.QPushButton(parent=Form)
        self.quit.setGeometry(QtCore.QRect(277, 554, 271, 32))
        self.quit.setObjectName("quit")
        self.discussion = QtWidgets.QPushButton(parent=Form)
        self.discussion.setGeometry(QtCore.QRect(277, 520, 271, 32))
        self.discussion.setObjectName("discussion")
        self.register_2 = QtWidgets.QPushButton(parent=Form)
        self.register_2.setGeometry(QtCore.QRect(10, 486, 251, 32))
        self.register_2.setObjectName("register_2")
        self.subject = QtWidgets.QPushButton(parent=Form)
        self.subject.setGeometry(QtCore.QRect(10, 554, 251, 32))
        self.subject.setObjectName("subject")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(11, 220, 541, 261))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.username = QtWidgets.QLineEdit(parent=self.widget)
        self.username.setObjectName("username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.username)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.password = QtWidgets.QLineEdit(parent=self.widget)
        self.password.setObjectName("password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password)
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.createTopicName = QtWidgets.QLineEdit(parent=self.widget)
        self.createTopicName.setObjectName("createTopicName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.createTopicName)
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10)
        self.deleteTopicName = QtWidgets.QLineEdit(parent=self.widget)
        self.deleteTopicName.setObjectName("deleteTopicName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deleteTopicName)
        self.label_12 = QtWidgets.QLabel(parent=self.widget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create.setText(_translate("Form", "CreateTopic"))
        self.reply.setText(_translate("Form", "Reply"))
        self.quit.setText(_translate("Form", "Delete"))
        self.discussion.setText(_translate("Form", "Discussion"))
        self.register_2.setText(_translate("Form", "Register"))
        self.subject.setText(_translate("Form", "Subject"))
        self.label.setText(_translate("Form", "UserName:"))
        self.label_2.setText(_translate("Form", "Password:"))
        self.label_11.setText(_translate("Form", "CreateTopic"))
        self.label_10.setText(_translate("Form", "DeleteTopic:"))
        self.label_12.setText(_translate("Form", "Reply:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
